'use strict';

/**
 * Builds the browser version of MedV into /medv at the repository root, ready
 * for GitHub Pages. No bundler, no toolchain: this script concatenates the
 * CommonJS modules in src/core into one file with a tiny module registry, and
 * copies the interface as-is.
 *
 *   node tools/build-web.js
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const REPO = path.join(ROOT, '..');
const OUT = process.env.MEDV_WEB_OUT || path.join(REPO, 'medv');
const CORE = path.join(ROOT, 'src', 'core');

/** Modules that only make sense on the desktop, replaced by a web variant. */
const ALIASES = {
  'core/db/index.web': 'core/db/index',
  'core/paths.web': 'core/paths',
  'core/services/backup.web': 'core/services/backup'
};
const SKIP = new Set(['core/db/index', 'core/paths', 'core/services/backup']);

function walk(dir, base = dir) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full, base));
    else if (entry.name.endsWith('.js')) out.push(full);
  }
  return out;
}

function moduleId(file) {
  return `core/${path.relative(CORE, file).split(path.sep).join('/')}`.replace(/\.js$/, '');
}

function buildCore(pkg) {
  const files = walk(CORE).sort();
  const parts = [];
  const included = [];

  // src/core/api.js reads the version out of package.json; give it one.
  parts.push(`define(["package.json"], function (module) {\n  module.exports = ${
    JSON.stringify({ name: pkg.name, productName: pkg.productName, version: pkg.version })};\n});`);
  for (const file of files) {
    const id = moduleId(file);
    if (SKIP.has(id)) continue;
    const source = fs.readFileSync(file, 'utf8');
    const ids = [id, ...(ALIASES[id] ? [ALIASES[id]] : [])];
    included.push(ids.join(' → '));
    parts.push(`define(${JSON.stringify(ids)}, function (module, exports, require) {\n${source}\n});`);
  }
  const runtime = `/* MedV core — generated by tools/build-web.js. Do not edit here. */
(function (global) {
  'use strict';
  var factories = {};
  var cache = {};

  function define(ids, factory) {
    for (var i = 0; i < ids.length; i += 1) factories[ids[i]] = factory;
  }

  function normalise(parts) {
    var out = [];
    for (var i = 0; i < parts.length; i += 1) {
      var piece = parts[i];
      if (piece === '' || piece === '.') continue;
      if (piece === '..') out.pop();
      else out.push(piece);
    }
    return out.join('/');
  }

  function resolve(from, request) {
    if (request.charAt(0) !== '.') {
      if (factories[request]) return request;
      if (factories[request + '/index']) return request + '/index';
      return request;
    }
    var base = from.split('/');
    base.pop();
    var id = normalise(base.concat(request.split('/')));
    if (factories[id]) return id;
    if (factories[id + '/index']) return id + '/index';
    return id;
  }

  function requireFrom(from) {
    return function (request) {
      var id = resolve(from, request);
      if (cache[id]) return cache[id].exports;
      var factory = factories[id];
      if (!factory) {
        var err = new Error("Cannot find module '" + request + "' from '" + from + "'");
        err.code = 'MODULE_NOT_FOUND';
        throw err;
      }
      var module = { exports: {} };
      cache[id] = module;
      factory(module, module.exports, requireFrom(id));
      return module.exports;
    };
  }

  ${parts.join('\n\n  ')}

  global.MedVCore = {
    require: requireFrom('core/entry'),
    modules: function () { return Object.keys(factories); }
  };
})(typeof globalThis !== 'undefined' ? globalThis : window);
`;
  return { code: runtime, included };
}

function copy(from, to) {
  fs.mkdirSync(path.dirname(to), { recursive: true });
  fs.copyFileSync(from, to);
}

function copyTree(from, to, filter = () => true) {
  for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
    const src = path.join(from, entry.name);
    const dest = path.join(to, entry.name);
    if (entry.isDirectory()) copyTree(src, dest, filter);
    else if (filter(src)) copy(src, dest);
  }
}

function main() {
  fs.rmSync(OUT, { recursive: true, force: true });
  fs.mkdirSync(OUT, { recursive: true });

  // 1. the interface, exactly as the desktop build uses it
  copyTree(path.join(ROOT, 'src', 'renderer'), OUT, (f) => !f.endsWith('index.html'));

  // 2. the business logic, as one generated file
  const pkg = require(path.join(ROOT, 'package.json'));
  const { code, included } = buildCore(pkg);
  fs.writeFileSync(path.join(OUT, 'js', 'core.bundle.js'), code);

  // 3. sql.js (SQLite compiled to WebAssembly)
  const vendor = path.join(ROOT, 'vendor');
  copy(path.join(vendor, 'sql-wasm.js'), path.join(OUT, 'vendor', 'sql-wasm.js'));
  copy(path.join(vendor, 'sql-wasm.wasm'), path.join(OUT, 'vendor', 'sql-wasm.wasm'));
  copy(path.join(vendor, 'sql.js-LICENSE'), path.join(OUT, 'vendor', 'sql.js-LICENSE'));

  // 4. the page shell, service worker and manifest
  copyTree(path.join(ROOT, 'web'), OUT);

  const version = pkg.version;
  const bridgePath = path.join(OUT, 'js', 'bridge.js');
  fs.writeFileSync(bridgePath, fs.readFileSync(bridgePath, 'utf8').replace('__VERSION__', version));
  const swPath = path.join(OUT, 'sw.js');
  const assets = listAssets(OUT).filter((f) => f !== 'sw.js');
  fs.writeFileSync(swPath, fs.readFileSync(swPath, 'utf8')
    .replace('__CACHE_VERSION__', `medv-v${version}-${Date.now().toString(36)}`)
    .replace('__ASSETS__', JSON.stringify(assets, null, 2)));

  console.log(`MedV web build → ${OUT}`);
  console.log(`  ${included.length} core modules, ${assets.length} files`);
}

function listAssets(dir, base = dir) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...listAssets(full, base));
    else out.push(path.relative(base, full).split(path.sep).join('/'));
  }
  return out.sort();
}

main();
