/* MedV offline cache. Generated by tools/build-web.js — do not edit here. */
const CACHE = 'medv-v1.0.0-mtzjkp1q';
const ASSETS = [
  "assets/icon-256.png",
  "assets/logo.png",
  "assets/mark.png",
  "css/app.css",
  "css/print.css",
  "css/tokens.css",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/icon-maskable-512.png",
  "index.html",
  "js/api.js",
  "js/app.js",
  "js/bridge.js",
  "js/calc.js",
  "js/core.bundle.js",
  "js/dom.js",
  "js/format.js",
  "js/icons.js",
  "js/nav.js",
  "js/pickers.js",
  "js/print.js",
  "js/router.js",
  "js/store.js",
  "js/ui.js",
  "js/views/backup.js",
  "js/views/billing.js",
  "js/views/customers.js",
  "js/views/dashboard.js",
  "js/views/doctors.js",
  "js/views/gst.js",
  "js/views/login.js",
  "js/views/money.js",
  "js/views/products.js",
  "js/views/purchaseEntry.js",
  "js/views/purchases.js",
  "js/views/reminders.js",
  "js/views/reports.js",
  "js/views/returns.js",
  "js/views/sales.js",
  "js/views/settings.js",
  "js/views/setup.js",
  "js/views/stock.js",
  "js/views/suppliers.js",
  "manifest.webmanifest",
  "vendor/sql-wasm.js",
  "vendor/sql-wasm.wasm",
  "vendor/sql.js-LICENSE"
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE)
      .then((cache) => cache.addAll(ASSETS.map((a) => new Request(a, { cache: 'reload' }))))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((names) => Promise.all(names.filter((n) => n !== CACHE).map((n) => caches.delete(n))))
      .then(() => self.clients.claim())
  );
});

/**
 * Cache first: the shop must open instantly and work with the connection
 * unplugged. A new version is picked up on the next visit.
 */
self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET' || new URL(request.url).origin !== self.location.origin) return;
  event.respondWith(
    caches.match(request, { ignoreSearch: true }).then((hit) => {
      if (hit) {
        // Refresh in the background so the next load has the newest files.
        fetch(request).then((fresh) => {
          if (fresh && fresh.ok) caches.open(CACHE).then((cache) => cache.put(request, fresh.clone()));
        }).catch(() => {});
        return hit;
      }
      return fetch(request)
        .then((response) => {
          if (response && response.ok) {
            const copy = response.clone();
            caches.open(CACHE).then((cache) => cache.put(request, copy));
          }
          return response;
        })
        .catch(() => caches.match('index.html'));
    })
  );
});
