#!/usr/bin/env python3
"""Assemble a buildable Flutter project.

The Android host (Gradle files, manifest, resources) is not kept in this
repository. It is generated by `flutter create` at build time so it always
matches the Flutter version doing the building — which is the difference
between an APK that builds in two years and one that does not.

This script takes that freshly generated shell and layers our app on top:

    flutter create --org com.lavidhawa --project-name lavi_billing <build-dir>
    python3 tool/prepare.py <build-dir>
    cd <build-dir> && flutter build apk --release

What it does:
  1. copies pubspec.yaml, analysis_options.yaml and lib/ into the shell
  2. copies ../billing-app into assets/www and rewrites the asset list
  3. swaps the generated MainActivity for ours (print / save / pick file)
  4. patches the manifest: app name, no cloud backup, no INTERNET permission
  5. draws the launcher icons
"""

import os
import re
import shutil
import sys
import xml.etree.ElementTree as ET

HERE = os.path.dirname(os.path.abspath(__file__))
PROJECT = os.path.dirname(HERE)
REPO = os.path.dirname(PROJECT)
WEB_APP = os.path.join(REPO, "billing-app")

PACKAGE = "com.lavidhawa.lavi_billing"
APP_LABEL = "Lavi Billing"
ANDROID_NS = "http://schemas.android.com/apk/res/android"
NS = "{%s}" % ANDROID_NS

# Files in billing-app/ that have no place inside an APK.
SKIP = {"README.md", "sw.js"}


def log(message):
    print("[prepare] %s" % message)


# --------------------------------------------------------------- dart side

def copy_app_sources(build):
    for name in ("pubspec.yaml", "analysis_options.yaml"):
        src = os.path.join(PROJECT, name)
        if os.path.exists(src):
            shutil.copy2(src, os.path.join(build, name))
            log("copied %s" % name)

    lib_dst = os.path.join(build, "lib")
    shutil.rmtree(lib_dst, ignore_errors=True)
    shutil.copytree(os.path.join(PROJECT, "lib"), lib_dst)
    log("copied lib/")


def drop_generated_test(build):
    """`flutter create` leaves a widget test for a MyApp that this project does
    not have, and it fails analysis. There is nothing to keep in it."""
    path = os.path.join(build, "test", "widget_test.dart")
    if os.path.exists(path):
        os.remove(path)
        log("removed the generated widget test")
    test_dir = os.path.join(build, "test")
    if os.path.isdir(test_dir) and not os.listdir(test_dir):
        os.rmdir(test_dir)


def copy_web_app(build):
    if not os.path.isdir(WEB_APP):
        raise SystemExit("billing-app/ not found at %s" % WEB_APP)

    dst = os.path.join(build, "assets", "www")
    shutil.rmtree(dst, ignore_errors=True)
    shutil.copytree(WEB_APP, dst, ignore=shutil.ignore_patterns(*SKIP))

    count = sum(len(files) for _, _, files in os.walk(dst))
    log("copied %d web app files into assets/www" % count)
    return dst


def rewrite_asset_list(build, www):
    """Flutter includes a declared directory's own files but not its
    subdirectories, so every directory has to be listed. Deriving the list from
    what is actually on disk means a new folder can never be silently missed."""
    dirs = set()
    for root, _, files in os.walk(www):
        if not files:
            continue
        rel = os.path.relpath(root, build).replace(os.sep, "/")
        dirs.add(rel + "/")

    block = "\n".join("    - %s" % d for d in sorted(dirs))
    path = os.path.join(build, "pubspec.yaml")
    with open(path, encoding="utf-8") as handle:
        text = handle.read()

    patched, hits = re.subn(
        r"(\n  assets:\n)(?:    - .*\n)+",
        lambda m: m.group(1) + block + "\n",
        text,
    )
    if not hits:
        raise SystemExit("pubspec.yaml has no 'assets:' list to rewrite")

    with open(path, "w", encoding="utf-8") as handle:
        handle.write(patched)
    log("declared %d asset directories" % len(dirs))


# ------------------------------------------------------------ android side

def install_activity(build):
    main = os.path.join(build, "android", "app", "src", "main")

    # Drop whatever `flutter create` generated (Kotlin by default).
    for language in ("kotlin", "java"):
        root = os.path.join(main, language)
        for dirpath, _, files in os.walk(root) if os.path.isdir(root) else []:
            for name in files:
                if name in ("MainActivity.kt", "MainActivity.java"):
                    os.remove(os.path.join(dirpath, name))
                    log("removed generated %s" % name)

    dst_dir = os.path.join(main, "java", *PACKAGE.split("."))
    os.makedirs(dst_dir, exist_ok=True)
    shutil.copy2(
        os.path.join(PROJECT, "android_host", "MainActivity.java"),
        os.path.join(dst_dir, "MainActivity.java"),
    )
    log("installed MainActivity.java at %s" % PACKAGE)

    xml_dir = os.path.join(main, "res", "xml")
    os.makedirs(xml_dir, exist_ok=True)
    shutil.copy2(
        os.path.join(PROJECT, "android_host", "data_rules.xml"),
        os.path.join(xml_dir, "data_rules.xml"),
    )
    log("installed backup rules")


def patch_manifest(build):
    path = os.path.join(build, "android", "app", "src", "main", "AndroidManifest.xml")
    ET.register_namespace("android", ANDROID_NS)
    tree = ET.parse(path)
    root = tree.getroot()

    # The app must not be able to reach the network.
    removed = 0
    for node in list(root.findall("uses-permission")):
        if node.get(NS + "name") == "android.permission.INTERNET":
            root.remove(node)
            removed += 1
    if removed:
        log("removed the INTERNET permission")

    application = root.find("application")
    if application is None:
        raise SystemExit("AndroidManifest.xml has no <application>")

    application.set(NS + "label", APP_LABEL)
    application.set(NS + "allowBackup", "false")
    application.set(NS + "fullBackupContent", "false")
    application.set(NS + "dataExtractionRules", "@xml/data_rules")
    application.set(NS + "usesCleartextTraffic", "false")

    activity = application.find("activity")
    if activity is not None:
        activity.set(NS + "name", ".MainActivity")
        activity.set(NS + "screenOrientation", "fullUser")
        activity.set(NS + "windowSoftInputMode", "adjustResize")

    tree.write(path, encoding="utf-8", xml_declaration=True)
    log("patched the manifest (label, backups off, no internet)")


def draw_icons(build):
    try:
        from PIL import Image, ImageDraw, ImageFont
    except ImportError:
        log("Pillow not installed — keeping the default Flutter icon")
        return

    navy = (29, 43, 69, 255)
    cream = (240, 243, 248, 255)

    def font(size):
        for path in (
            "/usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf",
            "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
        ):
            try:
                return ImageFont.truetype(path, size)
            except Exception:
                continue
        return ImageFont.load_default()

    def emblem(size, scale, background=None, radius_ratio=0.22):
        """The signboard plate: fork, plate marked DA, spoon."""
        s = size * 4
        image = Image.new("RGBA", (s, s), (0, 0, 0, 0))
        draw = ImageDraw.Draw(image)
        if background:
            draw.rounded_rectangle([0, 0, s - 1, s - 1],
                                   radius=int(s * radius_ratio), fill=background)

        c = s / 2.0
        r = s * scale
        w = max(2, int(s * 0.010))

        draw.ellipse([c - r, c - r, c + r, c + r], outline=cream, width=w * 2)
        inner = r * 0.74
        draw.ellipse([c - inner, c - inner, c + inner, c + inner], outline=cream, width=w)

        face = font(int(r * 0.9))
        box = draw.textbbox((0, 0), "DA", font=face)
        draw.text((c - (box[2] - box[0]) / 2 - box[0], c - (box[3] - box[1]) / 2 - box[1]),
                  "DA", font=face, fill=cream)

        top, bottom, tw = c - r * 1.05, c + r * 1.12, r * 0.13

        fx = c - r * 1.85
        for i in (-1, 0, 1):
            x = fx + i * r * 0.26
            draw.rounded_rectangle([x - tw / 2, top, x + tw / 2, top + r * 0.62],
                                   radius=tw / 2, fill=cream)
        draw.rounded_rectangle([fx - tw * 0.9, top + r * 0.44, fx + tw * 0.9, bottom],
                               radius=tw * 0.9, fill=cream)

        sx = c + r * 1.85
        draw.ellipse([sx - r * 0.27, top, sx + r * 0.27, top + r * 0.78], fill=cream)
        draw.rounded_rectangle([sx - tw * 0.9, top + r * 0.55, sx + tw * 0.9, bottom],
                               radius=tw * 0.9, fill=cream)

        return image.resize((size, size), Image.LANCZOS)

    res = os.path.join(build, "android", "app", "src", "main", "res")
    for name, px in (("mdpi", 48), ("hdpi", 72), ("xhdpi", 96),
                     ("xxhdpi", 144), ("xxxhdpi", 192)):
        folder = os.path.join(res, "mipmap-" + name)
        os.makedirs(folder, exist_ok=True)
        emblem(px, 0.145, background=navy).save(os.path.join(folder, "ic_launcher.png"))
    log("drew the launcher icons")


def main():
    if len(sys.argv) != 2:
        raise SystemExit("usage: prepare.py <build-dir>")

    build = os.path.abspath(sys.argv[1])
    if not os.path.isdir(os.path.join(build, "android")):
        raise SystemExit(
            "%s does not look like a Flutter project.\n"
            "Run `flutter create --org com.lavidhawa --project-name lavi_billing %s` first."
            % (build, build)
        )

    log("preparing %s" % build)
    copy_app_sources(build)
    drop_generated_test(build)
    www = copy_web_app(build)
    rewrite_asset_list(build, www)
    install_activity(build)
    patch_manifest(build)
    draw_icons(build)
    log("ready — run `flutter build apk --release` in %s" % build)


if __name__ == "__main__":
    main()
